In [2]:
#Create an array having consecutive natural numbers of size 6x3 and print it
import numpy as np
arr1=np.arange(18).reshape(6,3)
print(arr1)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [6]:
# Rename alll the coumns in the dataset as per your wish and save it in another dataframe and name it df2
import pandas as pd
df=pd.read_excel(r'C:\Users\ruhim\Downloads\Week 1 Dataset.xlsx')
df2=df.rename(columns={"Name":"Id","Income per month":"Salary","State":"State_name","Age":"Age_person","Sex":"Sex_person","Number of siblings":"Siblings"})
print(df2)

#After you have created df2, make the same changes in the original dataframe using the inplace.
df.rename(columns={"Name":"Id","Income per month":"Salary","State":"State_name","Age":"Age_person","Sex":"Sex_person","Number of siblings":"Siblings"},inplace=True)
print(df)

  Id  Salary     State_name  Age_person Sex_person  Siblings
0  A      50     Tamil Nadu          23          M         0
1  B      34      Karnataka          37          F         3
2  C      54     Tamil Nadu          35          F         1
3  D      24  Uttar Pradesh          26          F         4
4  E      19          Bihar          59          M         5
5  F      21          Bihar          48          M         6
6  G      40          Delhi          30          F         2
7  H      20  Uttar Pradesh          72          M        10
8  I      30      Telangana          22          F         0
9  J      18    Chattisgarh          42          M         7
  Id  Salary     State_name  Age_person Sex_person  Siblings
0  A      50     Tamil Nadu          23          M         0
1  B      34      Karnataka          37          F         3
2  C      54     Tamil Nadu          35          F         1
3  D      24  Uttar Pradesh          26          F         4
4  E      19          Bi

In [8]:
# Show only the columns information, sex and number of siblings.
df[["Sex_person","Siblings"]]

Sex_person  Siblings
0          M         0
1          F         3
2          F         1
3          F         4
4          M         5
5          M         6
6          F         2
7          M        10
8          F         0
9          M         7

In [9]:
# Use iloc method to print data from column 1 to 4 and rows 3 to 9
df.iloc[3:10,1:5]

Salary     State_name  Age_person Sex_person
3      24  Uttar Pradesh          26          F
4      19          Bihar          59          M
5      21          Bihar          48          M
6      40          Delhi          30          F
7      20  Uttar Pradesh          72          M
8      30      Telangana          22          F
9      18    Chattisgarh          42          M

In [10]:
# Find the total value count of number of siblings in the given dataset
df["Siblings"].value_counts()


0     2
10    1
7     1
6     1
5     1
4     1
3     1
2     1
1     1
Name: Siblings, dtype: int64

In [ ]:
# What are dependent and independent varibles in our dataset?

Number of siblings is a dependent variable and other attributes are independent variables.

In [ ]:
# Mention all your finding from the above given heatmap.

Income per month and number of siblings are negatively correlated ( As income per month increases, the number of siblings decreases)

Age and number of siblings are positively correlated (People who are older have more silings than younger ones)

Income per month and age are negatively correlated 